# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_parallel_kernel_matrix <- function(dataset, centroids, std, dataset_type) {
    .Call(`_RBFNN_rcpp_parallel_kernel_matrix`, dataset, centroids, std, dataset_type)
}

